//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhythmMonopoly.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("하위 포함 더미")]
        public string BotCategory01 {
            get {
                return ((string)(this["BotCategory01"]));
            }
            set {
                this["BotCategory01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("하위 포함 더미")]
        public string BotCategory02 {
            get {
                return ((string)(this["BotCategory02"]));
            }
            set {
                this["BotCategory02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("하위 포함 더미")]
        public string BotCategory03 {
            get {
                return ((string)(this["BotCategory03"]));
            }
            set {
                this["BotCategory03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("귀여운 ")]
        public string feelcontent1 {
            get {
                return ((string)(this["feelcontent1"]));
            }
            set {
                this["feelcontent1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("웅장한 ")]
        public string feelcontent2 {
            get {
                return ((string)(this["feelcontent2"]));
            }
            set {
                this["feelcontent2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("빠른 ")]
        public string feelcontent3 {
            get {
                return ((string)(this["feelcontent3"]));
            }
            set {
                this["feelcontent3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("무서운 ")]
        public string feelcontent4 {
            get {
                return ((string)(this["feelcontent4"]));
            }
            set {
                this["feelcontent4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("초고속 ")]
        public string feelcontent5 {
            get {
                return ((string)(this["feelcontent5"]));
            }
            set {
                this["feelcontent5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("동물")]
        public string bgacontent1 {
            get {
                return ((string)(this["bgacontent1"]));
            }
            set {
                this["bgacontent1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("식물")]
        public string bgacontent2 {
            get {
                return ((string)(this["bgacontent2"]));
            }
            set {
                this["bgacontent2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("보석")]
        public string bgacontent3 {
            get {
                return ((string)(this["bgacontent3"]));
            }
            set {
                this["bgacontent3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("곤충")]
        public string bgacontent4 {
            get {
                return ((string)(this["bgacontent4"]));
            }
            set {
                this["bgacontent4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("사람")]
        public string bgacontent5 {
            get {
                return ((string)(this["bgacontent5"]));
            }
            set {
                this["bgacontent5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("영어")]
        public string languagecontent1 {
            get {
                return ((string)(this["languagecontent1"]));
            }
            set {
                this["languagecontent1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("일본어")]
        public string languagecontent2 {
            get {
                return ((string)(this["languagecontent2"]));
            }
            set {
                this["languagecontent2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("한국어")]
        public string languagecontent3 {
            get {
                return ((string)(this["languagecontent3"]));
            }
            set {
                this["languagecontent3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent1_1 {
            get {
                return ((string)(this["dummycontent1_1"]));
            }
            set {
                this["dummycontent1_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent1_2 {
            get {
                return ((string)(this["dummycontent1_2"]));
            }
            set {
                this["dummycontent1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent1_3 {
            get {
                return ((string)(this["dummycontent1_3"]));
            }
            set {
                this["dummycontent1_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent2_1 {
            get {
                return ((string)(this["dummycontent2_1"]));
            }
            set {
                this["dummycontent2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent2_2 {
            get {
                return ((string)(this["dummycontent2_2"]));
            }
            set {
                this["dummycontent2_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent2_3 {
            get {
                return ((string)(this["dummycontent2_3"]));
            }
            set {
                this["dummycontent2_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent2_4 {
            get {
                return ((string)(this["dummycontent2_4"]));
            }
            set {
                this["dummycontent2_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent3_1 {
            get {
                return ((string)(this["dummycontent3_1"]));
            }
            set {
                this["dummycontent3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent3_2 {
            get {
                return ((string)(this["dummycontent3_2"]));
            }
            set {
                this["dummycontent3_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent3_3 {
            get {
                return ((string)(this["dummycontent3_3"]));
            }
            set {
                this["dummycontent3_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent3_4 {
            get {
                return ((string)(this["dummycontent3_4"]));
            }
            set {
                this["dummycontent3_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("더미")]
        public string dummycontent3_5 {
            get {
                return ((string)(this["dummycontent3_5"]));
            }
            set {
                this["dummycontent3_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HappyHome {
            get {
                return ((string)(this["HappyHome"]));
            }
            set {
                this["HappyHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("동시 수록 곡")]
        public string TopCategory01 {
            get {
                return ((string)(this["TopCategory01"]));
            }
            set {
                this["TopCategory01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("전자 음 많은 노래")]
        public string TopCategory02 {
            get {
                return ((string)(this["TopCategory02"]));
            }
            set {
                this["TopCategory02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("나나히라")]
        public string TopCategory03 {
            get {
                return ((string)(this["TopCategory03"]));
            }
            set {
                this["TopCategory03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("아침 알람으로 쓸 곡")]
        public string TopCategory04 {
            get {
                return ((string)(this["TopCategory04"]));
            }
            set {
                this["TopCategory04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("뭐적지")]
        public string TopCategory05 {
            get {
                return ((string)(this["TopCategory05"]));
            }
            set {
                this["TopCategory05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("몰루")]
        public string TopCategory06 {
            get {
                return ((string)(this["TopCategory06"]));
            }
            set {
                this["TopCategory06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TestColor {
            get {
                return ((global::System.Drawing.Color)(this["TestColor"]));
            }
            set {
                this["TestColor"] = value;
            }
        }
    }
}
