//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhythmMonopoly.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 에 수록된 곡")]
        public string BotCategory01 {
            get {
                return ((string)(this["BotCategory01"]));
            }
            set {
                this["BotCategory01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 에 수록된 콜라보 노래")]
        public string BotCategory02 {
            get {
                return ((string)(this["BotCategory02"]));
            }
            set {
                this["BotCategory02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 분위기 노래")]
        public string BotCategory03 {
            get {
                return ((string)(this["BotCategory03"]));
            }
            set {
                this["BotCategory03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("귀여운 ")]
        public string dummycontent5_1 {
            get {
                return ((string)(this["dummycontent5_1"]));
            }
            set {
                this["dummycontent5_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("웅장한 ")]
        public string dummycontent5_2 {
            get {
                return ((string)(this["dummycontent5_2"]));
            }
            set {
                this["dummycontent5_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("빠른 ")]
        public string dummycontent5_3 {
            get {
                return ((string)(this["dummycontent5_3"]));
            }
            set {
                this["dummycontent5_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("무서운 ")]
        public string dummycontent5_4 {
            get {
                return ((string)(this["dummycontent5_4"]));
            }
            set {
                this["dummycontent5_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("초고속 ")]
        public string dummycontent5_5 {
            get {
                return ((string)(this["dummycontent5_5"]));
            }
            set {
                this["dummycontent5_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("댕댕이")]
        public string dummycontent4_1 {
            get {
                return ((string)(this["dummycontent4_1"]));
            }
            set {
                this["dummycontent4_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("식물")]
        public string dummycontent4_2 {
            get {
                return ((string)(this["dummycontent4_2"]));
            }
            set {
                this["dummycontent4_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("보석")]
        public string dummycontent4_3 {
            get {
                return ((string)(this["dummycontent4_3"]));
            }
            set {
                this["dummycontent4_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("곤충")]
        public string dummycontent4_4 {
            get {
                return ((string)(this["dummycontent4_4"]));
            }
            set {
                this["dummycontent4_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("사람")]
        public string dummycontent4_5 {
            get {
                return ((string)(this["dummycontent4_5"]));
            }
            set {
                this["dummycontent4_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("영어")]
        public string dummycontent6_1 {
            get {
                return ((string)(this["dummycontent6_1"]));
            }
            set {
                this["dummycontent6_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("일본어")]
        public string dummycontent6_2 {
            get {
                return ((string)(this["dummycontent6_2"]));
            }
            set {
                this["dummycontent6_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("한국어")]
        public string dummycontent6_3 {
            get {
                return ((string)(this["dummycontent6_3"]));
            }
            set {
                this["dummycontent6_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARCAEA")]
        public string dummycontent1_1 {
            get {
                return ((string)(this["dummycontent1_1"]));
            }
            set {
                this["dummycontent1_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("디제이맥스")]
        public string dummycontent1_2 {
            get {
                return ((string)(this["dummycontent1_2"]));
            }
            set {
                this["dummycontent1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("벨루시티")]
        public string dummycontent1_3 {
            get {
                return ((string)(this["dummycontent1_3"]));
            }
            set {
                this["dummycontent1_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("이지투온")]
        public string dummycontent2_1 {
            get {
                return ((string)(this["dummycontent2_1"]));
            }
            set {
                this["dummycontent2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("그루브 코스터")]
        public string dummycontent2_2 {
            get {
                return ((string)(this["dummycontent2_2"]));
            }
            set {
                this["dummycontent2_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("뮤즈대쉬")]
        public string dummycontent2_3 {
            get {
                return ((string)(this["dummycontent2_3"]));
            }
            set {
                this["dummycontent2_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BMS")]
        public string dummycontent2_4 {
            get {
                return ((string)(this["dummycontent2_4"]));
            }
            set {
                this["dummycontent2_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("즐거운")]
        public string dummycontent3_1 {
            get {
                return ((string)(this["dummycontent3_1"]));
            }
            set {
                this["dummycontent3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("귀여운")]
        public string dummycontent3_2 {
            get {
                return ((string)(this["dummycontent3_2"]));
            }
            set {
                this["dummycontent3_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("씹덕같은")]
        public string dummycontent3_3 {
            get {
                return ((string)(this["dummycontent3_3"]));
            }
            set {
                this["dummycontent3_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("행복한")]
        public string dummycontent3_4 {
            get {
                return ((string)(this["dummycontent3_4"]));
            }
            set {
                this["dummycontent3_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("세기말")]
        public string dummycontent3_5 {
            get {
                return ((string)(this["dummycontent3_5"]));
            }
            set {
                this["dummycontent3_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HappyHome {
            get {
                return ((string)(this["HappyHome"]));
            }
            set {
                this["HappyHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("동시 수록 곡")]
        public string TopCategory01 {
            get {
                return ((string)(this["TopCategory01"]));
            }
            set {
                this["TopCategory01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("변속 곡")]
        public string TopCategory02 {
            get {
                return ((string)(this["TopCategory02"]));
            }
            set {
                this["TopCategory02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("솔직히 뭐적어야할지몰라서대충채워놨음")]
        public string TopCategory03 {
            get {
                return ((string)(this["TopCategory03"]));
            }
            set {
                this["TopCategory03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("바꿔서 쓰세요")]
        public string TopCategory04 {
            get {
                return ((string)(this["TopCategory04"]));
            }
            set {
                this["TopCategory04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("바꿔서 쓰세요")]
        public string TopCategory05 {
            get {
                return ((string)(this["TopCategory05"]));
            }
            set {
                this["TopCategory05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("바꿔서 쓰세요")]
        public string TopCategory06 {
            get {
                return ((string)(this["TopCategory06"]));
            }
            set {
                this["TopCategory06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TestColor {
            get {
                return ((global::System.Drawing.Color)(this["TestColor"]));
            }
            set {
                this["TestColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AlphaNum {
            get {
                return ((int)(this["AlphaNum"]));
            }
            set {
                this["AlphaNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ConsoNum {
            get {
                return ((int)(this["ConsoNum"]));
            }
            set {
                this["ConsoNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TopNum {
            get {
                return ((int)(this["TopNum"]));
            }
            set {
                this["TopNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BottomNum {
            get {
                return ((int)(this["BottomNum"]));
            }
            set {
                this["BottomNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Randomize {
            get {
                return ((bool)(this["Randomize"]));
            }
            set {
                this["Randomize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GoldenFix {
            get {
                return ((bool)(this["GoldenFix"]));
            }
            set {
                this["GoldenFix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 이(가) BGA에 나오는 곡")]
        public string BotCategory04 {
            get {
                return ((string)(this["BotCategory04"]));
            }
            set {
                this["BotCategory04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 느낌이 나는 곡")]
        public string BotCategory05 {
            get {
                return ((string)(this["BotCategory05"]));
            }
            set {
                this["BotCategory05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 로 된 보컬 언어 곡")]
        public string BotCategory06 {
            get {
                return ((string)(this["BotCategory06"]));
            }
            set {
                this["BotCategory06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int GoldenNum {
            get {
                return ((int)(this["GoldenNum"]));
            }
            set {
                this["GoldenNum"] = value;
            }
        }
    }
}
